// Central source of truth for backend capability flags
export const capabilities = {
  home: false,
  projects: false,
  computers: false,
  recent: false,
  sharing: false,
  publicLinks: false,
  spam: false,
  folderUpload: false,
  folderMove: false,
  thumbnails: false,
  billing: false,
  createFolder: true,
  fileUpload: true,
  fileDownload: true,
  fileMove: true,
  searchFiles: true,
  starred: true,
  trash: true,
  gridView: true,
  listView: true,
  localSort: true,
  localTypeFilter: true,
  darkMode: true,
} as const;
