import { apiFetch } from "@/lib/api/client";
import { ApiResponse } from "@/lib/api/envelope";
import {
  UserShare,
  PublicLink,
  CreateSharePayload,
  UpdateSharePayload,
  CreatePublicLinkPayload,
  ResolvedPublicResource,
} from "./schemas";

// ── User-to-User Shares API ──────────────────────────────────────────────────

/**
 * Share a file or folder with another user by their registered email address.
 */
export async function createShare(payload: CreateSharePayload): Promise<ApiResponse<UserShare>> {
  return apiFetch<ApiResponse<UserShare>>("/shares", {
    method: "POST",
    json: payload,
  });
}

/**
 * Retrieve all active shares received by the currently authenticated user.
 */
export async function getReceivedShares(): Promise<ApiResponse<UserShare[]>> {
  return apiFetch<ApiResponse<UserShare[]>>("/shares/received");
}

/**
 * Retrieve all shares sent/created by the currently authenticated user.
 */
export async function getSentShares(): Promise<ApiResponse<UserShare[]>> {
  return apiFetch<ApiResponse<UserShare[]>>("/shares/sent");
}

/**
 * Update permission level or expiration date for an existing share.
 */
export async function updateShare(
  id: string,
  payload: UpdateSharePayload
): Promise<ApiResponse<UserShare>> {
  return apiFetch<ApiResponse<UserShare>>(`/shares/${id}`, {
    method: "PATCH",
    json: payload,
  });
}

/**
 * Revoke/delete a user share.
 */
export async function revokeShare(id: string): Promise<ApiResponse<{ message: string }>> {
  return apiFetch<ApiResponse<{ message: string }>>(`/shares/${id}`, {
    method: "DELETE",
  });
}

// ── Public Links API ─────────────────────────────────────────────────────────

/**
 * Generate a public unauthenticated link for a file or folder.
 */
export async function createPublicLink(
  payload: CreatePublicLinkPayload
): Promise<ApiResponse<PublicLink>> {
  return apiFetch<ApiResponse<PublicLink>>("/public", {
    method: "POST",
    json: payload,
  });
}

/**
 * Retrieve all public links generated by the current user.
 */
export async function getPublicLinks(): Promise<ApiResponse<PublicLink[]>> {
  return apiFetch<ApiResponse<PublicLink[]>>("/public");
}

/**
 * Resolve and fetch public resource metadata and presigned URL by token.
 * Can be accessed unauthenticated by any visitor holding the token.
 */
export async function getPublicResource(
  token: string
): Promise<ApiResponse<ResolvedPublicResource>> {
  return apiFetch<ApiResponse<ResolvedPublicResource>>(`/public/${token}`);
}

/**
 * Revoke/delete a public link.
 */
export async function revokePublicLink(id: string): Promise<ApiResponse<{ message: string }>> {
  return apiFetch<ApiResponse<{ message: string }>>(`/public/${id}`, {
    method: "DELETE",
  });
}
